#!/bin/bash
# Shared setup for live E2E suites. Callers provide KIMI_API_KEY before sourcing.

if [ -z "${KIMI_API_KEY:-}" ]; then
  echo "KIMI_API_KEY must be set before sourcing scripts/e2e/common.sh" >&2
  return 1
fi

E2E_SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
EXT_DIR="$(cd -- "$E2E_SCRIPT_DIR/../.." && pwd)"
PI_BIN="${PI_BIN:-$(command -v pi)}"

export KIMI_CODE_DEBUG="${KIMI_CODE_DEBUG:-1}"
export KIMI_E2E_VERBOSE="${KIMI_E2E_VERBOSE:-1}"
export KIMI_E2E_MODEL="${KIMI_E2E_MODEL:-kimi-coding/kimi-for-coding}"
export KIMI_E2E_WIRE_MODEL="${KIMI_E2E_WIRE_MODEL:-kimi-for-coding}"
export KIMI_E2E_CACHE_INTERVALS="${KIMI_E2E_CACHE_INTERVALS:-60,300}"
export KIMI_E2E_CACHE_KEY="${KIMI_E2E_CACHE_KEY:-pi-provider-kimi-code-e2e-$$-$(date +%s)}"
export KIMI_E2E_CACHE_REPEAT="${KIMI_E2E_CACHE_REPEAT:-2000}"
export KIMI_E2E_SKIP_CACHE="${KIMI_E2E_SKIP_CACHE:-0}"
export KIMI_E2E_SKIP_CACHE_MATRIX="${KIMI_E2E_SKIP_CACHE_MATRIX:-0}"
export KIMI_E2E_SKIP_DUAL_BREAKPOINT="${KIMI_E2E_SKIP_DUAL_BREAKPOINT:-0}"
export KIMI_E2E_SKIP_CACHE_KEY_SEMANTICS="${KIMI_E2E_SKIP_CACHE_KEY_SEMANTICS:-0}"
export KIMI_E2E_SKIP_CACHE_CHAIN="${KIMI_E2E_SKIP_CACHE_CHAIN:-0}"
export KIMI_E2E_SKIP_CROSS_PROTOCOL="${KIMI_E2E_SKIP_CROSS_PROTOCOL:-0}"
export KIMI_E2E_SKIP_SYSTEM_TOOLS_CACHE="${KIMI_E2E_SKIP_SYSTEM_TOOLS_CACHE:-0}"
export KIMI_E2E_SKIP_LARGE_DELTA="${KIMI_E2E_SKIP_LARGE_DELTA:-0}"
export KIMI_E2E_SKIP_TTL_UPPER="${KIMI_E2E_SKIP_TTL_UPPER:-1}"
export KIMI_E2E_TTL_UPPER_INTERVALS="${KIMI_E2E_TTL_UPPER_INTERVALS:-1800}"
export KIMI_E2E_SKIP_BLOCK_SIZE_SWEEP="${KIMI_E2E_SKIP_BLOCK_SIZE_SWEEP:-0}"
export KIMI_E2E_SKIP_TOOLS_CHANGE="${KIMI_E2E_SKIP_TOOLS_CHANGE:-0}"
export KIMI_E2E_SKIP_SMALL_BOUNDARY="${KIMI_E2E_SKIP_SMALL_BOUNDARY:-0}"
export KIMI_E2E_SKIP_OPENAI_CACHE_BOUNDARY="${KIMI_E2E_SKIP_OPENAI_CACHE_BOUNDARY:-0}"
export KIMI_E2E_SKIP_RETENTION_NONE_PROVIDER="${KIMI_E2E_SKIP_RETENTION_NONE_PROVIDER:-0}"
export KIMI_E2E_SKIP_USAGE_FIELDS="${KIMI_E2E_SKIP_USAGE_FIELDS:-0}"
export KIMI_E2E_SKIP_NON_PROMPT_PARAMS="${KIMI_E2E_SKIP_NON_PROMPT_PARAMS:-0}"
export KIMI_E2E_SKIP_MULTIMODAL_CACHE="${KIMI_E2E_SKIP_MULTIMODAL_CACHE:-0}"
export KIMI_E2E_SKIP_CONCURRENT_CACHE="${KIMI_E2E_SKIP_CONCURRENT_CACHE:-0}"
export KIMI_E2E_SKIP_VERY_LARGE_CACHE="${KIMI_E2E_SKIP_VERY_LARGE_CACHE:-1}"
export KIMI_E2E_VERY_LARGE_REPEAT="${KIMI_E2E_VERY_LARGE_REPEAT:-12000}"
export KIMI_E2E_SKIP_DEVICE_ID_CACHE="${KIMI_E2E_SKIP_DEVICE_ID_CACHE:-0}"

KIMI_HEADERS=(
  -H "User-Agent: KimiCLI/1.44.0"
  -H "X-Msh-Platform: kimi_cli"
  -H "X-Msh-Version: 1.44.0"
)
BASE_URL="${KIMI_CODE_BASE_URL:-https://api.kimi.com/coding/v1}"
BASE_URL="${BASE_URL%/}"

log() {
  printf '%s\n' "$*"
}

if [ "$KIMI_E2E_VERBOSE" = "1" ]; then
  log "Using extension: $EXT_DIR"
  log "Using pi binary: $PI_BIN"
  "$PI_BIN" --version
  log "Model under test: $KIMI_E2E_MODEL (wire: $KIMI_E2E_WIRE_MODEL)"
fi
